// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toyzz.Infrastructure;

#nullable disable

namespace Toyzz.Infrastructure.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Toyzz.Domain.AggregatesModel.Blogs.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadPortrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2514),
                            Name = "name_1",
                            Url = "http://5000:name_1"
                        },
                        new
                        {
                            Id = 2,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2537),
                            Name = "name_2",
                            Url = "http://5000:name_2"
                        },
                        new
                        {
                            Id = 3,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2539),
                            Name = "name_3",
                            Url = "http://5000:name_3"
                        },
                        new
                        {
                            Id = 4,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2541),
                            Name = "name_4",
                            Url = "http://5000:name_4"
                        },
                        new
                        {
                            Id = 5,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2543),
                            Name = "name_5",
                            Url = "http://5000:name_5"
                        },
                        new
                        {
                            Id = 6,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2547),
                            Name = "name_6",
                            Url = "http://5000:name_6"
                        },
                        new
                        {
                            Id = 7,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2549),
                            Name = "name_7",
                            Url = "http://5000:name_7"
                        },
                        new
                        {
                            Id = 8,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2551),
                            Name = "name_8",
                            Url = "http://5000:name_8"
                        },
                        new
                        {
                            Id = 9,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2553),
                            Name = "name_9",
                            Url = "http://5000:name_9"
                        },
                        new
                        {
                            Id = 10,
                            HeadPortrait = "",
                            JoinDate = new DateTime(2023, 7, 19, 14, 34, 49, 659, DateTimeKind.Local).AddTicks(2557),
                            Name = "name_10",
                            Url = "http://5000:name_10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
